// client-angular/src/app/alt/alt.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-alt',
  templateUrl: './alt.component.html',
  styleUrls: ['./alt.component.css'],
})
export class AltComponent {
  @Input() alt = 1000;
  @Input() displayVisual = true;
}

<div *ngIf="displayVisual; else text" class="alt">
  <input
    class="range"
    aria-label="inp"
    type="range"
    min="0"
    max="3000"
    [value]="alt"
  />
  <ul class="numbers">
    <li>3000</li>
    <li>2000</li>
    <li>1000</li>
    <li>0</li>
  </ul>
</div>

<ng-template #text>
  <div>ALT: {{ alt }}</div>
</ng-template>

// client-react/src/components/alt/Alt.jsx
import "./alt.css";

export default function Alt({ val, displayVisual }) {
  return (
    displayVisual ? (
      <div className="alt">
        <input
        readOnly
          className="range"
          type="range"
          value={val}
          min={0}
          max={3000}
          name=""
          id=""
        />
        <ul className="numbers">
          <li>3000</li>
          <li>2000</li>
          <li>1000</li>
          <li>0</li>
        </ul>
      </div>
    )  : <p>ALT: {val}</p>
  );
}
