// client-angular/src/app/switch/switch.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-switch',
  templateUrl: './switch.component.html',
  styleUrls: ['./switch.component.css'],
})
export class SwitchComponent {
  @Input() display = {
    visual: true
  };
  @Input() setVisual(mode: boolean){}
}

<div class="switch">
  <button (click)="setVisual(true)" [ngClass]="{ selected: display.visual }">Visual</button>
  <button (click)="setVisual(false)" [ngClass]="{ selected: !display.visual }">Text</button>
</div>

// client-react/src/components/switch/Switch.jsx
import "./switch.css";

export default function Switch({ displayVisual, setDisplayVisual }) {
  return (
    <div className="switch">
      <button
        className={displayVisual ? "selected" : ""}
        onClick={() => setDisplayVisual(true)}
      >
        Visual
      </button>
      <button
        className={displayVisual? "" : "selected"}
        onClick={() => setDisplayVisual(false)}
      >
        Text
      </button>
    </div>
  );
}
